config/routes.rb
Rails.application.routes.draw do

  root 'index#vote_results'
  post 'vote' => 'index#new_vote'
  post 'reset' => 'index#reset'
  get 'results' => 'index#vote_results'
  get 'result_items' => 'index#result_items', as: 'fetch_items'
  get 'question_count' => 'index#question_count'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  def self.create_from_params!(params)
    v=Vote.new
    v.from = params[:From]
    v.to = params[:To]
    v.sid = params[:MessageSid]
    v.body = params[:Body]
    v.question = params[:Body].split(" ").first.upcase.strip
    v.answer = params[:Body].partition(" ").last.upcase.strip
    v.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  skip_before_filter :verify_authenticity_token  

  def index
    render :text=>"Vote here"
  end

  def new_vote
    emots=["😃","😄","😋","😍","🙉","🙌","✌","✔","⭐","🌹","🌻","🌼","🍦","🎈","🎉","🐼","👀","👅","👊","💜"]
    if params[:Body].blank?
      render :text=>"<Response><Sms>No SMS body received</Sms></Response>"
    elsif params[:Body].split(" ").length==1
      render :text=>"<Response><Sms>Please enter the question number or letter, followed by a space, then your answer.</Sms></Response>"
    else
      v=Vote.create_from_params!(params)
      render :text=>"<Response><Sms>Answer received #{emots.sample}</Sms></Response>"
    end
  end

  def vote_results
    @questions =  Vote.select(:question).distinct.order(:question)
  end
  
  def reset
    Vote.delete_all
    redirect_to("/results")
  end
  
  def result_items
    @q = Vote.where("question=?", params[:question]).first
     # respond_to do |format|
     #   format.js
     # end
  end
  
  def question_count
    count =  Vote.select(:question).distinct.length
    render :json => count
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/_response.html.erb
<div class="row">
	<div class="4u">
	
		<!-- Sidebar -->
			<div id="sidebar">
				<section class="widget thumbnails">
					<h3>Question <%= q.question %></h3>
					<%= column_chart Vote.where("question=?", q.question).group(:answer).count.sort.to_h,  id: "chart-#{q.question}" %>
				</section>
			</div>
	
	</div>
	<div class="8u important(collapse)">

		<!-- Content -->
			<div id="content">
				<section class="last">
					<h3>Question <%= q.question %> Responses</h3>
					<p>
						<table>
					        <tr>
					            <th>Answer</th>
					            <th>From</th>
								<th>Date</th>
					        </tr>
							
						<% Vote.where("question=?", q.question).order(:answer).each do |vote| %>
						<tr>
							<td><%= vote.answer %></td>
							<td><%= vote.from %></td>
							<td><%= localize(vote.created_at, :format => :long) %></td>
						</tr>
						<% end %>
					</table>
						
					</p>
				</section>
			</div>

	</div>
</div>

app/views/index/result_items.html.erb
<%= render :partial => 'response', locals: {q: @q}, :remote => true %>

app/views/index/result_items.js.erb
  $("#<%= @q.question %>").html("<%= escape_javascript(render partial: 'response', locals: { q: @q } ) %>"); 

app/views/index/vote_results.html.erb
<!DOCTYPE HTML>
<!--
	Verti by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>SMS Quiz</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<!--[if lte IE 8]><script src="css/ie/html5shiv.js"></script><![endif]-->
		<script src="js/jquery.min.js"></script>
		<script src="js/jquery.dropotron.min.js"></script>
		<script src="js/skel.min.js"></script>
		<script src="js/skel-layers.min.js"></script>
		<script src="js/init.js"></script>
		<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
		<noscript>
			<link rel="stylesheet" href="css/skel.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-desktop.css" />
		</noscript>
		
		<style>
		table, th {
		    background-color: #aaa;
			padding: 3px 10px;
		}
		tbody {
		    background-color: #ddd;
		    height: 250px;
		    overflow: auto;
		}
		td {
		    padding: 3px 10px;
		}

		thead > tr, tbody{
		    display:block;}
		</style>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
	</head>
	<body class="homepage">

		<!-- Header -->
			<div id="header-wrapper">
				<header id="header" class="container">
				
					<!-- Logo -->
						<div id="logo">
							<h1>Quiz!</h1>
Text responses to: <br/><b><span style="font-size:18px; line-height:0;"><%= Rails.application.config.twilio_number_label %></span></b>
						</div>
					
					<!-- Nav -->
						<nav id="nav">
							<ul>
								<li><a href="results">Refresh Results</a></li>
								<li><a href="javascript:if (confirm('Are you sure you want to reset all responses?  Data will be deleted.'))  document.forms[0].submit();">Reset Responses</a></li>
							</ul>
						</nav>
				</header>
			</div>
		
		<!-- Main -->
			<div id="main-wrapper">
				<div class="container">
					<% if @questions.empty? %>
					<h2>No SMS received yet</h2>
					<% end %>
					<% @questions.each do |q|%>
						<div id="<%= q.question %>">
							<%= render :partial => 'response', locals: {q: q}, :remote => true %>
						</div>
					<% end %>
				</div>
			</div>
			<form id="resetForm" action="/reset" method="POST"></form>

<script>
  $(document).ready(function(){
    setInterval(updateCharts,5000);
 });

  function updateCharts(){
	  
	  $.ajax({
	      url:"/question_count",  
	      success:function(data) {
			  if (data > <%= @questions.length %>){
				  document.location.reload();
			  }
	      }
	    });
		
	  <% @questions.each do |q|%>
		  $("#<%=q.question%>").load("<%=fetch_items_path(question: q.question)%>"); 
	  <% end %>
  }
  
</script>

	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SalesSms</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>